name: Build-Wasm
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 升级到 v4
      - name: Install Rust
        run: rustup target add wasm32-wasi
      - name: Build
        run: cargo build --target wasm32-wasi --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # 必须是 v4，否则必报错
        with:
          name: gcore-binary
          path: target/wasm32-wasi/release/*.wasm
